### ISSUE TITLE
Feature Request : Import from CSV

### ISSUE THREAD

**Issue by n-v-o** [Smartlist-app/Smartlist#9]
Impressive project. I plan on testing it out and will be happy to provide feedback and ideas, and contribute in any way I can. One great feature would be the ability to import, since you do have an export feature . I'd love to be able to import my current WIP inventory to get a better feel for this to avoid duplicating effort..

**Comment by ManuTheCoder** [comment]
Sure! On my todo list :white_check_mark:

**Comment by ManuTheCoder** [comment]
So, currently, you can upload a CSV file for the kitchen 
(go to dashboard>settings>backup>Upload CSV)
